### ISSUE TITLE
Make it easier to guess the right word

### ISSUE THREAD

**Issue by alimanfoo** [harbi811/I-Spy-Game#2]
Currently it's very hard for the player to guess the right word within seven guesses, because (unless you peek at the source code) you don't have any way to narrow down the set of possible words you should be thinking of.

Perhaps it would improve playability if there was a way that the player could ask for a clue. Perhaps this clue could be revealing another letter from the word.

Another approach could be to divide the game up into different categories, like "animals", for example. Before beginning a round, the player chooses which category to play. Then at least you know you should be trying to guess the name of an animal, not just any word beginning with the given letter.

You might want to split this into different issues, or rescope this depending on what your preferred approach is - just thought I would raise an issue to start discussion :)

**Comment by harbi811** [comment]
Thank you very much for the feedback. I divided the words into four categories namely; animals, fruits, places and expert (which consists of random words). Later on, I will implement revealing another letter from the word if the user fails at the first attempt.
